package dsw.gerumap.app.gui.swing.errorLogger;

public enum EventType {
    CANNOT_ADD_CHILD, CANNOT_REMOVE, CANNOT_SET_AUTHOR, NAME_CANNOT_BE_EMPTY,
    NOTHING_IS_SELECTED, CANNOT_SET_NAME,MUST_OPET_MINDMAP,MUST_CHOOSE_PROJECT,
    MUST_CHOOSE_MINDMAP
}
